### ISSUE TITLE
The Configuration order causes PFCP Association Request Failure

### ISSUE THREAD

**Issue by gatici** [omec-project/smf#196]
The following configuration order in webconsole causes PFCP Association Setup failure.

- Create a network slice with empty device group
- Create a device group
- Create a subscriber

SMF log:

`2023-11-30T20:55:48.294Z [smf] 2023-11-30T20:55:48Z [ERRO][SMF][PFCP] Handle PFCP Association Setup success Response, DNN mismatch, [internet] is not configured`

Please check the following issue for more details:
https://github.com/omec-project/webconsole/issues/89

**Comment by gruyaume** [comment]
It looks like this issue is due to the fact that the DNN list in a given UPF is added when the network slice is created but never edited afterwards when the device group gets added to the network slice.
